/**
 * Public types for CMS data.
 *
 * These are all derived from the query result types generated by
 * `npx sanity typegen generate` (see `sanity.types.ts`), so the frontend and the
 * GROQ projections can never drift apart. Re-run typegen after changing a query
 * or the schema.
 */
import type {
  AboutPageQueryResult,
  AcademicsPageQueryResult,
  AdmissionsPageQueryResult,
  ClassRoutinePageQueryResult,
  HomePageQueryResult,
  NavigationQueryResult,
  PageSeoQueryResult,
  SiteSettingsQueryResult,
} from './sanity.types'

export type {NavigationQueryResult, PageSeoQueryResult, SiteSettingsQueryResult}

/** Strips `null` from a type. */
type Val<T> = NonNullable<T>
/** The non-nullable element type of an array field. */
type Item<T> = NonNullable<T> extends (infer U)[] ? NonNullable<U> : never

/* -------------------------------------------------------------------------- */
/* Queries                                                                    */
/* -------------------------------------------------------------------------- */

export type HomePageData = HomePageQueryResult
export type AboutPageData = AboutPageQueryResult
export type SiteSettings = Val<SiteSettingsQueryResult>
export type Navigation = Val<NavigationQueryResult>

/* -------------------------------------------------------------------------- */
/* Primitives                                                                 */
/* -------------------------------------------------------------------------- */

/**
 * A CMS image: the Sanity asset reference plus the editor's crop and hotspot.
 * `src/sanity/lib/image` turns it into a sized URL on the Sanity CDN.
 */
export type SanityImage = NonNullable<
  Extract<HomeSection, {_type: 'aboutStorySection'}>['image']
>

export type Link = Val<Extract<HomeSection, {_type: 'aboutStorySection'}>['link']>
export type Button = Val<Extract<HomeSection, {_type: 'heroSection'}>['primaryButton']>
export type ButtonVariant = Button['variant']

/** Page-level and site-level SEO, as returned by the metadata query. */
export type Seo = Val<Val<Val<PageSeoQueryResult>['page']>['seo']>
export type PageSeo = {
  page: Seo | null
  site: Seo | null
  /** `siteSettings.brand.name`, used to brand titles and structured data. */
  brandName: string | null
}

/* -------------------------------------------------------------------------- */
/* Site settings                                                              */
/* -------------------------------------------------------------------------- */

export type Brand = Val<SiteSettings['brand']>
export type ContactBlock = Val<SiteSettings['contact']>
export type SocialLink = Item<SiteSettings['socialLinks']>
export type ContactListItem = Item<Val<SiteSettings['footer']>['contactItems']>
export type Footer = Val<SiteSettings['footer']>
export type SocialPreviewCard = Val<Footer['socialCard']>
export type MapCard = Val<Footer['map']>
export type FloatingContact = Val<SiteSettings['floatingContact']>

/* -------------------------------------------------------------------------- */
/* Navigation                                                                 */
/* -------------------------------------------------------------------------- */

export type TopBar = Val<Navigation['topBar']>
export type TopBarLink = Item<TopBar['contactLinks']>
export type HeaderNav = Val<Navigation['header']>
export type NavItem = Item<HeaderNav['items']>
export type NavChildLink = Item<NavItem['children']>

/* -------------------------------------------------------------------------- */
/* Home page                                                                  */
/* -------------------------------------------------------------------------- */

export type HomePage = Val<HomePageData['home']>
export type HomeSection = Item<HomePage['sections']>

export type HeroSection = Extract<HomeSection, {_type: 'heroSection'}>
export type StatsBarSection = Extract<HomeSection, {_type: 'statsBarSection'}>
export type FeaturesSection = Extract<HomeSection, {_type: 'featuresSection'}>
export type AboutStorySection = Extract<HomeSection, {_type: 'aboutStorySection'}>
export type StudentSpotlightSection = Extract<HomeSection, {_type: 'studentSpotlightSection'}>
export type AdmissionBannerSection = Extract<HomeSection, {_type: 'admissionBannerSection'}>
export type NewsSection = Extract<HomeSection, {_type: 'newsSection'}>
export type ReviewBarSection = Extract<HomeSection, {_type: 'reviewBarSection'}>

/* -------------------------------------------------------------------------- */
/* Repeated items                                                             */
/* -------------------------------------------------------------------------- */

export type SectionHeader = Val<FeaturesSection['header']>
export type HeroSlide = Item<HeroSection['slides']>
export type StatItem = Item<StatsBarSection['items']>
export type FeatureCard = Item<FeaturesSection['cards']>
export type StudentSpotlight = Item<StudentSpotlightSection['students']>
export type NewsPost = Item<NewsSection['posts']>

/* -------------------------------------------------------------------------- */
/* About page                                                                  */
/* -------------------------------------------------------------------------- */

export type AboutPage = Val<AboutPageData['about']>
export type AboutSection = Item<AboutPage['sections']>

export type PageHeroSection = Extract<AboutSection, {_type: 'pageHeroSection'}>
export type PrincipalSection = Extract<AboutSection, {_type: 'principalSection'}>
export type PeopleGridSection = Extract<AboutSection, {_type: 'peopleGridSection'}>
export type PillarsSection = Extract<AboutSection, {_type: 'pillarsSection'}>
export type PageCtaSection = Extract<AboutSection, {_type: 'pageCtaSection'}>

/** A referenced `person` document, dereferenced by the query. */
export type Person = NonNullable<PrincipalSection['principal']>

export type BreadcrumbItem = Item<PageHeroSection['crumbs']>
export type PillarCard = Item<PillarsSection['pillars']>

/* -------------------------------------------------------------------------- */
/* Admissions page                                                             */
/* -------------------------------------------------------------------------- */

export type AdmissionsPageData = AdmissionsPageQueryResult
export type AdmissionsPage = Val<AdmissionsPageData['admissions']>
export type AdmissionsSection = Item<AdmissionsPage['sections']>

export type ProcessStepsSection = Extract<AdmissionsSection, {_type: 'processStepsSection'}>
export type ProcessStep = Item<ProcessStepsSection['steps']>
export type FeatureImageSection = Extract<AdmissionsSection, {_type: 'featureImageSection'}>
export type CalloutSection = Extract<AdmissionsSection, {_type: 'calloutSection'}>
export type FaqSection = Extract<AdmissionsSection, {_type: 'faqSection'}>
export type FaqItem = Item<FaqSection['items']>

/* -------------------------------------------------------------------------- */
/* Academics page                                                             */
/* -------------------------------------------------------------------------- */

export type AcademicsPageData = AcademicsPageQueryResult
export type AcademicsPage = Val<AcademicsPageData['academics']>
export type AcademicsSection = Item<AcademicsPage['sections']>

export type ClassTableSection = Extract<AcademicsSection, {_type: 'classTableSection'}>
export type ClassTableColumns = Val<ClassTableSection['columnLabels']>

/** A referenced `classLevel` document, dereferenced by the query. */
export type ClassLevel = Item<ClassTableSection['classes']>
/* -------------------------------------------------------------------------- */
/* Class routine page                                                          */
/* -------------------------------------------------------------------------- */

export type ClassRoutinePageData = ClassRoutinePageQueryResult
export type ClassRoutinePage = Val<ClassRoutinePageData['routine']>
export type ClassRoutineSection = Item<ClassRoutinePage['sections']>

export type RoutineSection = Extract<ClassRoutineSection, {_type: 'routineSection'}>

/** A referenced `classRoutine` document, dereferenced by the query. */
export type ClassRoutine = NonNullable<NonNullable<RoutineSection['routines']>[number]>
export type ClassRoutineRow = Item<NonNullable<ClassRoutine['rows']>>