/**
 * GROQ for the Home page and the site-wide singletons.
 *
 * Every field the frontend renders is projected here, in one place, so the
 * Studio "Vision" plugin and the frontend always agree on shape. Types for these
 * queries are generated by `npx sanity typegen generate` into
 * `src/sanity/types/sanity.types.ts`.
 */
import {defineQuery} from 'next-sanity'

/** Projection for a field whose type is our `imageWithAlt` object. */
const imageWithAltProjection = /* groq */ `{
  "asset": image.asset,
  "crop": image.crop,
  "hotspot": image.hotspot,
  alt
}`

const linkProjection = /* groq */ `{
  _key,
  label,
  url,
  newTab
}`

const buttonProjection = /* groq */ `{
  _key,
  label,
  url,
  newTab,
  variant
}`

const seoProjection = /* groq */ `{
  metaTitle,
  metaDescription,
  "shareImage": shareImage${imageWithAltProjection},
  canonicalUrl,
  noIndex
}`

const contactListItemProjection = /* groq */ `{
  _key,
  icon,
  label,
  href
}`

/* -------------------------------------------------------------------------- */
/* Site-wide singletons                                                       */
/* -------------------------------------------------------------------------- */

export const siteSettingsQuery = defineQuery(`*[_type == "siteSettings"][0]{
  "id": _id,
  "brand": brand{
    "logo": logo${imageWithAltProjection},
    name,
    acronym,
    establishedLabel
  },
  contact{
    address,
    phoneLabel,
    phoneHref,
    mobileLabel,
    mobileHref,
    emailLabel,
    emailHref
  },
  socialLinks[]{ _key, icon, label, url },
  footer{
    enabled,
    tagline,
    contactItems[]${contactListItemProjection},
    quickLinksTitle,
    quickLinks[]${linkProjection},
    socialTitle,
    socialCard{
      bannerLabel,
      "image": image${imageWithAltProjection},
      title,
      subtitle,
      description,
      url
    },
    mapTitle,
    map{ buttonLabel, url, pinLabel, areaLabel },
    copyrightText,
    legalLinks[]${linkProjection}
  },
  floatingContact{ enabled, bubbleLabel, icon, url, ariaLabel },
  seo${seoProjection}
}`)

export const navigationQuery = defineQuery(`*[_type == "navigation"][0]{
  "id": _id,
  topBar{
    enabled,
    contactLinks[]{ _key, icon, label, url, newTab },
    badge,
    notice${buttonProjection}
  },
  header{
    enabled,
    homeUrl,
    brandSubline,
    items[]{
      _key,
      label,
      url,
      isCurrentPage,
      showChevron,
      highlight,
      children[]{ _key, icon, label, url }
    },
    cta${buttonProjection},
    mobileMenuTitle,
    mobileMenuCta${buttonProjection}
  }
}`)

/* -------------------------------------------------------------------------- */
/* Home page                                                                  */
/* -------------------------------------------------------------------------- */

const heroSlideProjection = /* groq */ `{
  _key,
  "image": image${imageWithAltProjection},
  isVisible
}`

const statItemProjection = /* groq */ `{
  _key,
  value,
  label,
  isSmaller
}`

const featureCardProjection = /* groq */ `{
  _key,
  icon,
  badge,
  useAmberIcon,
  title,
  description,
  isVisible
}`

const studentProjection = /* groq */ `{
  "id": _id,
  name,
  classLabel,
  "photo": photo${imageWithAltProjection},
  cohortLabel,
  schoolName,
  note,
  isVisible
}`

const newsPostProjection = /* groq */ `{
  "id": _id,
  title,
  category,
  excerpt,
  "image": image${imageWithAltProjection},
  link${linkProjection},
  isVisible
}`

/* -------------------------------------------------------------------------- */
/* Inner pages                                                                 */
/* -------------------------------------------------------------------------- */

const breadcrumbItemProjection = /* groq */ `{
  _key,
  label,
  url
}`

/**
 * A referenced `person` document. `_id` is projected as `id` because the frontend
 * needs the real document id to build the click-to-edit target on a person card.
 */
const personProjection = /* groq */ `{
  "id": _id,
  name,
  designation,
  role,
  badge,
  photoPlaceholderLabel,
  "photo": photo${imageWithAltProjection},
  shortBio,
  message,
  quote,
  quoteAttribution,
  isVisible
}`

/** Site-wide SEO fallbacks, used by any page without its own values. */
export const defaultSeoQuery = defineQuery(`*[_type == "siteSettings"][0]{seo${seoProjection}}`)

/**
 * SEO values for `generateMetadata`, for any page singleton.
 *
 * `$type` is the page's document type (`homePage`, `aboutPage`, …) so every page
 * shares one query rather than each declaring a near-identical copy.
 *
 * Fetched with stega disabled — invisible characters inside `<title>` or
 * `<meta content>` look fine in a browser but corrupt search engine results and
 * social scrapes.
 */
export const pageSeoQuery = defineQuery(`{
  "page": *[_type == $type][0]{seo${seoProjection}},
  "site": *[_type == "siteSettings"][0]{seo${seoProjection}}
}`)

/**
 * One flat projection covering every section type. Sections are discriminated by
 * `_type`, so each component reads only the fields it needs.
 */
const homeSectionProjection = /* groq */ `sections[]{
  _key,
  _type,
  enabled,

  // heroSection
  eyebrow,
  heading,
  description,
  highlightBadge,
  autoplaySeconds,
  primaryButton${buttonProjection},
  secondaryButton${buttonProjection},
  "slides": slides[isVisible != false]${heroSlideProjection},

  // statsBarSection
  items[]${statItemProjection},

  // featuresSection
  header{ heading, subheading },
  cards[isVisible != false]${featureCardProjection},

  // aboutStorySection
  "image": image${imageWithAltProjection},
  body,

  // link / badge fields shared by several sections
  "link": link${linkProjection},
  metaText,
  badge,
  anchorId,

  // studentSpotlightSection
  "students": students[]->${studentProjection},

  // newsSection
  "posts": posts[]->${newsPostProjection},

  // reviewBarSection
  brandLabel,
  score,
  summary,
  stars,

  "cta": cta${buttonProjection}
}`

/**
 * Everything the Home page needs in one round trip: site chrome, navigation and
 * the page's own content.
 */
export const homePageQuery = defineQuery(`{
  "siteSettings": ${siteSettingsQuery},
  "navigation": ${navigationQuery},
  "home": *[_type == "homePage"][0]{
    "id": _id,
    internalTitle,
    ${homeSectionProjection},
    seo${seoProjection}
  }
}`)

/**
 * One flat projection covering every inner-page section type, mirroring
 * `homeSectionProjection`. Sections are discriminated by `_type`, so each
 * component reads only the fields it needs.
 */
const aboutSectionProjection = /* groq */ `sections[]{
  _key,
  _type,
  enabled,

  // pageHeroSection
  heading,
  subheading,
  crumbs[]${breadcrumbItemProjection},

  // principalSection
  header{ heading, subheading },
  "principal": principal->${personProjection},

  // peopleGridSection
  anchorId,
  "people": people[]->${personProjection},
  emptyStateText,

  // pillarsSection
  pillars[]{ _key, icon, tone, title, description },

  // pageCtaSection
  badge,

  "cta": cta${buttonProjection},
  primaryButton${buttonProjection},
  secondaryButton${buttonProjection}
}`

/**
 * Everything the About page needs in one round trip: site chrome, navigation and
 * the page's own content. Same shape as `homePageQuery`, so the page component
 * reads identically to the Home page component.
 */
export const aboutPageQuery = defineQuery(`{
  "siteSettings": ${siteSettingsQuery},
  "navigation": ${navigationQuery},
  "about": *[_type == "aboutPage"][0]{
    "id": _id,
    internalTitle,
    ${aboutSectionProjection},
    seo${seoProjection}
  }
}`)
