/**
 * GROQ for the Home page and the site-wide singletons.
 *
 * Every field the frontend renders is projected here, in one place, so the
 * Studio "Vision" plugin and the frontend always agree on shape. Types for these
 * queries are generated by `npx sanity typegen generate` into
 * `src/sanity/types/sanity.types.ts`.
 */
import {defineQuery} from 'next-sanity'

/** Projection for a field whose type is our `imageWithAlt` object. */
const imageWithAltProjection = /* groq */ `{
  "asset": image.asset,
  "crop": image.crop,
  "hotspot": image.hotspot,
  alt
}`

const linkProjection = /* groq */ `{
  _key,
  label,
  url,
  newTab
}`

const buttonProjection = /* groq */ `{
  _key,
  label,
  url,
  newTab,
  variant
}`

const seoProjection = /* groq */ `{
  metaTitle,
  metaDescription,
  "shareImage": shareImage${imageWithAltProjection},
  canonicalUrl,
  appendSiteName,
  noIndex
}`

const contactListItemProjection = /* groq */ `{
  _key,
  icon,
  label,
  href
}`

/* -------------------------------------------------------------------------- */
/* Site-wide singletons                                                       */
/* -------------------------------------------------------------------------- */

export const siteSettingsQuery = defineQuery(`*[_type == "siteSettings"][0]{
  "id": _id,
  "brand": brand{
    "logo": logo${imageWithAltProjection},
    name,
    acronym,
    establishedLabel
  },
  contact{
    address,
    phoneLabel,
    phoneHref,
    mobileLabel,
    mobileHref,
    emailLabel,
    emailHref
  },
  postalAddress{
    streetAddress,
    addressLocality,
    addressRegion,
    addressCountry
  },
  socialLinks[]{ _key, icon, label, url },
  footer{
    enabled,
    tagline,
    contactItems[]${contactListItemProjection},
    quickLinksTitle,
    quickLinks[]${linkProjection},
    socialTitle,
    socialCard{
      bannerLabel,
      "image": image${imageWithAltProjection},
      title,
      subtitle,
      description,
      url
    },
    mapTitle,
    map{ buttonLabel, url, pinLabel, areaLabel },
    copyrightText,
    legalLinks[]${linkProjection}
  },
  floatingContact{ enabled, bubbleLabel, icon, url, ariaLabel },
  seo${seoProjection}
}`)

export const navigationQuery = defineQuery(`*[_type == "navigation"][0]{
  "id": _id,
  topBar{
    enabled,
    contactLinks[]{ _key, icon, label, url, newTab },
    badge,
    notice${buttonProjection}
  },
  header{
    enabled,
    homeUrl,
    brandSubline,
    items[]{
      _key,
      label,
      url,
      isCurrentPage,
      showChevron,
      highlight,
      children[]{ _key, icon, label, url }
    },
    cta${buttonProjection},
    mobileMenuTitle,
    mobileMenuCta${buttonProjection}
  }
}`)

/* -------------------------------------------------------------------------- */
/* Home page                                                                  */
/* -------------------------------------------------------------------------- */

const heroSlideProjection = /* groq */ `{
  _key,
  "image": image${imageWithAltProjection},
  isVisible
}`

const statItemProjection = /* groq */ `{
  _key,
  value,
  label,
  isSmaller
}`

const featureCardProjection = /* groq */ `{
  _key,
  icon,
  "iconImage": iconImage${imageWithAltProjection},
  badge,
  useAmberIcon,
  title,
  description,
  isVisible
}`

const studentProjection = /* groq */ `{
  "id": _id,
  name,
  classLabel,
  "photo": photo${imageWithAltProjection},
  cohortLabel,
  schoolName,
  note,
  isVisible
}`

const newsPostProjection = /* groq */ `{
  "id": _id,
  title,
  category,
  excerpt,
  "image": image${imageWithAltProjection},
  link${linkProjection},
  isVisible
}`

/* -------------------------------------------------------------------------- */
/* Inner pages                                                                 */
/* -------------------------------------------------------------------------- */

const breadcrumbItemProjection = /* groq */ `{
  _key,
  label,
  url
}`

/**
 * A referenced `person` document. `_id` is projected as `id` because the frontend
 * needs the real document id to build the click-to-edit target on a person card.
 */
const personProjection = /* groq */ `{
  "id": _id,
  name,
  designation,
  role,
  badge,
  photoPlaceholderLabel,
  "photo": photo${imageWithAltProjection},
  shortBio,
  message,
  quote,
  quoteAttribution,
  isVisible
}`

/** Site-wide SEO fallbacks, used by any page without its own values. */
export const defaultSeoQuery = defineQuery(`*[_type == "siteSettings"][0]{seo${seoProjection}}`)

/**
 * SEO values for `generateMetadata`, for any page singleton.
 *
 * `$type` is the page's document type (`homePage`, `aboutPage`, …) so every page
 * shares one query rather than each declaring a near-identical copy.
 *
 * `brandName` comes back with it because the title composer needs the school's
 * own name to brand a title that does not already carry it.
 *
 * Fetched with stega disabled — invisible characters inside `<title>` or
 * `<meta content>` look fine in a browser but corrupt search engine results and
 * social scrapes.
 */
export const pageSeoQuery = defineQuery(`{
  "page": *[_type == $type][0]{seo${seoProjection}},
  "site": *[_type == "siteSettings"][0]{seo${seoProjection}},
  "brandName": *[_type == "siteSettings"][0].brand.name
}`)

/**
 * Published pages for the XML sitemap.
 *
 * Read through the plain client rather than `sanityFetch`, on purpose: this must
 * never return draft content, even when the request happens to carry a Draft
 * Mode cookie. `_updatedAt` is the real last-edit time, so `lastModified` in the
 * sitemap is never invented.
 */
export const sitemapQuery = defineQuery(`*[_type in $types && !(_id in path("drafts.**"))]{
  _type,
  _updatedAt,
  "noIndex": seo.noIndex
}`)

/**
 * One flat projection covering every section type. Sections are discriminated by
 * `_type`, so each component reads only the fields it needs.
 */
const homeSectionProjection = /* groq */ `sections[]{
  _key,
  _type,
  enabled,

  // heroSection
  eyebrow,
  heading,
  description,
  highlightBadge,
  autoplaySeconds,
  primaryButton${buttonProjection},
  secondaryButton${buttonProjection},
  "slides": slides[isVisible != false]${heroSlideProjection},

  // statsBarSection
  items[]${statItemProjection},

  // featuresSection
  header{ heading, subheading },
  cards[isVisible != false]${featureCardProjection},

  // aboutStorySection
  "image": image${imageWithAltProjection},
  body,

  // link / badge fields shared by several sections
  "link": link${linkProjection},
  metaText,
  badge,
  anchorId,

  // studentSpotlightSection
  "students": students[]->${studentProjection},

  // newsSection
  "posts": posts[]->${newsPostProjection},

  // reviewBarSection
  brandLabel,
  score,
  summary,
  stars,

  "cta": cta${buttonProjection}
}`

/**
 * Everything the Home page needs in one round trip: site chrome, navigation and
 * the page's own content.
 */
export const homePageQuery = defineQuery(`{
  "siteSettings": ${siteSettingsQuery},
  "navigation": ${navigationQuery},
  "home": *[_type == "homePage"][0]{
    "id": _id,
    internalTitle,
    ${homeSectionProjection},
    seo${seoProjection}
  }
}`)

/**
 * One flat projection covering every inner-page section type, mirroring
 * `homeSectionProjection`. Sections are discriminated by `_type`, so each
 * component reads only the fields it needs.
 */
const aboutSectionProjection = /* groq */ `sections[]{
  _key,
  _type,
  enabled,

  // pageHeroSection
  heading,
  subheading,
  appearance,
  eyebrowIcon,
  eyebrow,
  crumbs[]${breadcrumbItemProjection},
  buttons[]${buttonProjection},

  // principalSection
  header{ heading, subheading },
  "principal": principal->${personProjection},

  // peopleGridSection
  anchorId,
  "people": people[]->${personProjection},
  emptyStateText,

  // pillarsSection
  pillars[]{ _key, icon, tone, title, description },

  // pageCtaSection
  badge,

  "cta": cta${buttonProjection},
  primaryButton${buttonProjection},
  secondaryButton${buttonProjection}
}`

/**
 * Everything the About page needs in one round trip: site chrome, navigation and
 * the page's own content. Same shape as `homePageQuery`, so the page component
 * reads identically to the Home page component.
 */
export const aboutPageQuery = defineQuery(`{
  "siteSettings": ${siteSettingsQuery},
  "navigation": ${navigationQuery},
  "about": *[_type == "aboutPage"][0]{
    "id": _id,
    internalTitle,
    ${aboutSectionProjection},
    seo${seoProjection}
  }
}`)

/**
 * One flat projection covering every Admissions page section type, mirroring the
 * other two section projections. Shared fields (heading, subheading, buttons,
 * anchorId) appear once; each component reads only what it needs.
 */
const admissionsSectionProjection = /* groq */ `sections[]{
  _key,
  _type,
  enabled,

  // shared across several section types
  anchorId,

  // pageHeroSection
  heading,
  subheading,
  appearance,
  eyebrowIcon,
  eyebrow,
  crumbs[]${breadcrumbItemProjection},
  buttons[]${buttonProjection},

  // processStepsSection
  header{ heading, subheading },
  steps[]{ _key, title, description, isHighlighted },
  
  // featureImageSection
  "image": image${imageWithAltProjection},
  caption,
  width,

  // calloutSection
  tone,
  body,
  buttonIcon,

  // faqSection
  items[]{ _key, question, answer, isOpenByDefault },

  // pageCtaSection
  badge,

  "button": button${buttonProjection},
  buttons[]${buttonProjection},
  primaryButton${buttonProjection},
  secondaryButton${buttonProjection}
}`

/**
 * Everything the Admissions page needs in one round trip: site chrome, navigation
 * and the page's own content.
 */
export const admissionsPageQuery = defineQuery(`{
  "siteSettings": ${siteSettingsQuery},
  "navigation": ${navigationQuery},
  "admissions": *[_type == "admissionsPage"][0]{
    "id": _id,
    internalTitle,
    ${admissionsSectionProjection},
    seo${seoProjection}
  }
}`)

/**
 * A referenced `classLevel` document. `_id` is projected as `id` so a table row
 * can be its own click-to-edit target.
 */
const classLevelProjection = /* groq */ `{
  "id": _id,
  name,
  ageRange,
  medium,
  focus,
  sortOrder,
  isVisible
}`

const classTableColumnsProjection = /* groq */ `{ class, age, medium, focus }`

/**
 * A referenced `classRoutine` document.
 *
 * The class name is dereferenced through `classLevel` so it is never duplicated,
 * and the day columns and rows come from the routine itself.
 */
const classRoutineProjection = /* groq */ `{
  "id": _id,
  "className": classLevel->name,
  session,
  days,
  rows[]{ _key, time, label, kind, cells },
  sortOrder,
  isVisible
}`

/** One flat projection covering every Academics page section type. */
const academicsSectionProjection = /* groq */ `sections[]{
  _key,
  _type,
  enabled,
  anchorId,

  // pageHeroSection
  heading,
  subheading,
  appearance,
  showIconWatermark,
  eyebrowIcon,
  eyebrow,
  crumbs[]${breadcrumbItemProjection},
  buttons[]${buttonProjection},

  // classTableSection
  header{ heading, subheading },
  columnLabels${classTableColumnsProjection},
  "classes": classes[]->${classLevelProjection},
  emptyStateText,

  // pillarsSection (icon card grid)
  pillars[]{ _key, icon, tone, title, description },

  // pageCtaSection
  badge,

  primaryButton${buttonProjection},
  secondaryButton${buttonProjection}
}`

/** Everything the Academics page needs in one round trip. */
export const academicsPageQuery = defineQuery(`{
  "siteSettings": ${siteSettingsQuery},
  "navigation": ${navigationQuery},
  "academics": *[_type == "academicsPage"][0]{
    "id": _id,
    internalTitle,
    ${academicsSectionProjection},
    seo${seoProjection}
  }
}`)

/** One flat projection covering every Class routine page section type. */
const classRoutinePageSectionProjection = /* groq */ `sections[]{
  _key,
  _type,
  enabled,
  anchorId,

  // pageHeroSection
  heading,
  subheading,
  appearance,
  showIconWatermark,
  eyebrowIcon,
  eyebrow,
  crumbs[]${breadcrumbItemProjection},
  buttons[]${buttonProjection},

  // routineSection
  header{ heading, subheading },
  "routines": routines[]->${classRoutineProjection},
  printButtonLabel,
  footnote,
  emptyStateText,

  // pillarsSection (icon card grid)
  pillars[]{ _key, icon, tone, title, description },

  // pageCtaSection
  badge,

  primaryButton${buttonProjection},
  secondaryButton${buttonProjection}
}`

/** Everything the Class routine page needs in one round trip. */
export const classRoutinePageQuery = defineQuery(`{
  "siteSettings": ${siteSettingsQuery},
  "navigation": ${navigationQuery},
  "routine": *[_type == "classRoutinePage"][0]{
    "id": _id,
    internalTitle,
    ${classRoutinePageSectionProjection},
    seo${seoProjection}
  }
}`)

/** Everything the Branch page needs in one round trip. */
export const branchPageQuery = defineQuery(`{
  "siteSettings": ${siteSettingsQuery},
  "navigation": ${navigationQuery},
  "branch": *[_type == "branchPage"][0]{
    "id": _id,
    hero{ eyebrow, heading, text, button${buttonProjection}, "image": image${imageWithAltProjection} },
    features{ enabled, items[]{ _key, icon, title, text } },
    about{ enabled, "image": image${imageWithAltProjection}, eyebrow, heading, paragraphs,
      button${buttonProjection} },
    programs{ enabled, eyebrow, heading, items[]{ _key, icon, title, text } },
    teachers{ enabled, eyebrow, heading,
      items[]{ _key, name, role, "photo": photo${imageWithAltProjection} } }
  }
}`)

/** Everything the Complaint Box page needs in one round trip. */
export const complaintPageQuery = defineQuery(`{
  "siteSettings": ${siteSettingsQuery},
  "navigation": ${navigationQuery},
  "complaint": *[_type == "complaintPage"][0]{
    "id": _id,
    internalTitle,
    heading,
    intro
  }
}`)

/** Everything the Contact page needs in one round trip. */
export const contactPageQuery = defineQuery(`{
  "siteSettings": ${siteSettingsQuery},
  "navigation": ${navigationQuery},
  "contact": *[_type == "contactPage"][0]{
    "id": _id,
    hero{ enabled, heading, subheading, appearance, showIconWatermark, eyebrow, eyebrowIcon,
      crumbs[]${breadcrumbItemProjection}, buttons[]${buttonProjection} },
    infoCard{ heading, items[]{ _key, icon, label, value, note }, button${buttonProjection} },
    mapCard{ title, address, rating, reviewCount, pinLabel, landmarks, attribution, mapUrl,
      button${buttonProjection} },
    form,
    review{ enabled, rating, headline, text, button${buttonProjection} }
  }
}`)
